# fly.toml app configuration file generated for timeline-mono-silent-butterfly-4090 on 2024-08-19T23:05:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timeline-mono-silent-butterfly-4090'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
